build:
  environment:
      go: 'go1.9.2'
  nodes:
    coverage:
      tests:
        override:
          - command: make all
            coverage:
              file: cover.out
              format: go-cc