language: go
addons:
  apt:
    packages:
      - libpcap-dev
go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master

env:
  - DEP_VERSION="X.X.X"
 before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep
  
 install:
  - dep ensure
  
script:
  - make all

notifications:
  email:
    on_success: change
    on_failure: never