language: go

env:
  - DEP_VERSION="0.4.1"

addons:
  apt:
    packages:
      - libpcap-dev

go:
  - "1.x"
  - "1.9"
  - "1.10.x"
  - master

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  
install:
  - dep ensure

script:
  - make all

notifications:
  email:
    on_success: change
    on_failure: never